### ISSUE TITLE
Union types

### ISSUE THREAD

**Issue by brendt** [spatie/typed#23]
```php
T::union(T::int(), T::Float());

T::union(T::generic(Post::class), T::int(), T::string());
```

Edit: change `compound` to `union`

**Comment by morrisonlevi** [comment]
Trying to clarify your intent, here. Given the following code:

```php
$c = new Collection(T::compound(T::generic(Post::class), T::int(), T::string()));
$c[] = ?;
```

This is saying that valid types of things to put in place of the `?` are:

  * A `Post`
  * OR an `int`
  * OR a string

Is that correct? If so the terminology is a `union`; see [Wikipedia's tagged union article](https://en.wikipedia.org/wiki/Tagged_union).

**Comment by brendt** [comment]
Your interpretation is indeed right, and thanks for pointing that out! I'll change the naming!
